[plugins]
  [plugins.cri]
    [plugins.cri.containerd]
      snapshotter = "overlayfs"
      [plugins.cri.containerd.default_runtime]
        runtime_type = "io.containerd.runtime.v1.linux"
        runtime_engine = "/var/vcap/packages/runtime-runc/bin/runc"
        runtime_root = ""
      [plugins.cri.containerd.untrusted_workload_runtime]
        runtime_type = "io.containerd.runtime.v1.linux"
        runtime_engine = "/var/vcap/packages/runtime-runc/bin/runsc"
        runtime_root = "/var/vcap/data/k8s/runtime-runc"
      [plugins.cri.containerd.gvisor]
        runtime_type = "io.containerd.runtime.v1.linux"
        runtime_engine = "/var/vcap/packages/runtime-runc/bin/runsc"
        runtime_root = "/var/vcap/data/k8s/runtime-runc"
    [plugins.cri.cni]
      conf_dir = "/var/vcap/jobs/net-<%= p('cni') %>/etc/cni/net.d"
      bin_dir = "/var/vcap/packages/containerd/bin"
    [plugins.cri.registry]
      [plugins.cri.registry.configs]
       <% p('mirrors').each do |mirror,data| %><% if data %><% if data['insecure_skip_verify'] %>
        [plugins.cri.registry.configs."<%= mirror %>".tls]
          insecure_skip_verify = <%= data['insecure_skip_verify']%>
       <% end %><% end %><% end %>
       <% p('mirrors').each do |mirror,data| %><% if data %><% if data['tls']%>
              [plugins.cri.registry.configs."<%= mirror%>".tls]
                ca_file =  /var/vcap/packages/containerd/"<%= mirror%>_ca.pem%>"
                cert_file=  /var/vcap/packages/containerd/"<%= mirror%>_ca.pem%>"
                key_file =  /var/vcap/packages/containerd/"<%= mirror%>_ca.pem%>"
               <% end %>
               <% end %><% end %>
       <% p('mirrors').each do |mirror,data| %><% if data%><% if data['auth'] %>
       [plugins.cri.registry.configs.auths."<%= mirror%>"]
         <% if data['auth']['username']%>username = "<%= data['auth']['username']%>"<%end %>
         <% if data['auth']['password']%>password = "<%= data['auth']['password']%>"<%end %>
         <% if data['auth']['auth']%>auth = "<%= data['auth']['auth']%>"<%end %>
         <% if data['auth']['identitytoken']%>identitytoken = "<%= data['auth']['identitytoken']%>"<%end %>
        <% end %><% end %>
        <% end %>
      [plugins.cri.registry.mirrors]
        <% p('mirrors').each do |mirror,data| %><% if data%>
        [plugins.cri.registry.mirrors."<%= mirror%>"]
          endpoint = ["<%= data['url'] %>"]
          <% end %>
        <% end %>

# persistent data location
root = "/var/vcap/store/k8s/runtime-runc"
# runtime state information (MUST be ephemeral; cannot persist between reboots)
state = "/var/vcap/data/k8s/runtime-runc"


