[plugins]
  [plugins.cri]
    [plugins.cri.containerd]
      snapshotter = "overlayfs"
      [plugins.cri.containerd.default_runtime]
        runtime_type = "io.containerd.runtime.v1.linux"
        runtime_engine = "/var/vcap/packages/runtime-runc/bin/runc"
        runtime_root = ""
      [plugins.cri.containerd.untrusted_workload_runtime]
        runtime_type = "io.containerd.runtime.v1.linux"
        runtime_engine = "/var/vcap/packages/runtime-runc/bin/runsc"
        runtime_root = "/var/vcap/data/k8s/runtime-runc"
      [plugins.cri.containerd.gvisor]
        runtime_type = "io.containerd.runtime.v1.linux"
        runtime_engine = "/var/vcap/packages/runtime-runc/bin/runsc"
        runtime_root = "/var/vcap/data/k8s/runtime-runc"
    [plugins.cri.cni]
      conf_dir = "/var/vcap/jobs/net-<%= p('cni') %>/etc/cni/net.d"
      bin_dir = "/var/vcap/packages/containerd/bin"
    [plugins.cri.registry]
      [plugins.cri.registry.configs]
       <% p('mirrors', []).each do |mirror| %>
       <% if mirror['insecure_skip_verify']%
        [plugins.cri.registry.configs."<%= mirror['name']%>".tls]
          <% if mirror['insecure_skip_verify']insecure_skip_verify = mirror['insecure_skip_verify']<%end %>
       <% end %>
       <% end %>
       <% p('mirrors', []).each do |mirror| %>
       <% if mirror['auth']%
       [plugins.cri.registry.configs.auths."<%= mirror['name']%>"]
         <% if mirror['auth'].['username']%>username = "mirror['auth'].['username']"<%end %>
         <% if mirror['auth'].['password']%>password = "mirror['auth'].['password']"<%end %>
         <% if mirror['auth'].['auth']%>auth = "mirror['auth'].['auth']" <%end %>
         <% if mirror['auth'].['identitytoken']%>identitytoken = "mirror['auth'].['identitytoken']"<%end %>
        <% end %>
        <% end %>
      [plugins.cri.registry.mirrors]
        <% p('mirrors', []).each do |mirror| %>
        [plugins.cri.registry.mirrors."<%= mirror['name']%>"]
          endpoint = ["<%= mirror['url'] %>"]
        <% end %>

# persistent data location
root = "/var/vcap/store/k8s/runtime-runc"
# runtime state information (MUST be ephemeral; cannot persist between reboots)
state = "/var/vcap/data/k8s/runtime-runc"


